#========================================================
# character: sender/accepter/puller
role: "sender"
#========================================================
sender:
  dir: "/home/wjq/桌面/pilotgo相关/PilotGo-plugin-logs/"
  user: "wjq"
  ip: "10.41.107.29"
#========================================================
accepter:
  dir: ""
  user: ""
  ip: ""
#========================================================
puller:
  addr: "192.168.75.136:19876"
  https: false
# peried web
  pullmethod: "web"
# unit: second
  pullperiod: 30
  dir: "/root/pilotgo相关/PilotGo-plugin-logs/"
  user: "root"
  ip: "192.168.75.136"
